### ISSUE TITLE
Popup with wrong header text 'Approve' on instead of 'Reject'	

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1718]
Reported by Sonali Goyal at https://mifosforge.jira.com/browse/MIFOSX-2317

On Checker Inbox and Tasks page under Checker Inbox Tab on clicking on Reject button the pop up appears with header 'Approve' on it instead of 'Reject'.

![error](https://cloud.githubusercontent.com/assets/23022667/21387878/c2b975a0-c79f-11e6-9c66-8ddae7927a48.png)
![error2](https://cloud.githubusercontent.com/assets/23022667/21387879/c2c04dd0-c79f-11e6-9ada-80f5198c8e60.png)

**Comment by mbj36** [comment]
Fixed

**Comment by jonathanzhang53** [comment]
This still persists for me on the demo server.
![reject error](https://user-images.githubusercontent.com/41968151/48295611-29d45580-e453-11e8-9192-3179f5e9cf50.gif)

**Comment by santoshconflux** [comment]
Please check you fetched latest code from Community App develop branch.

**Comment by AgnessMeena** [comment]
@santoshconflux @mbj36 Hi, still persists for me even after fetched the latest code, 
Can you share with me the PR id of this issue.

**Comment by santoshconflux** [comment]
We have created another ticket for this in order to make it generalization
