### ISSUE TITLE
Reskin&oldSkin: For non-super users, In loan Reschedule page 'Submit' button is not displaying

### ISSUE THREAD

**Issue by santoshmath** [openMF/community-app#1972]
> Create a role with all loan rescheduling , portfolio and loan transactions permisions.
>Create an user with this role
> Login with the user
>Try to 'Reschedule' any loan.
>On Loan reschedule page, 'Submit' button is not getting displayed. 

Similar Issue but related to Foreclosure:
https://github.com/openMF/community-app/issues/1836

**Comment by jhonatanbds** [comment]
this issue should've been fixed in another patch, I can actually see the button 
![image](https://cloud.githubusercontent.com/assets/17839018/24062992/7c2f3152-0b3c-11e7-91c2-9bf2b86ca2d4.png)

**Comment by mbj36** [comment]
This might be in new_reskin branch @jhonatanbds

**Comment by jhonatanbds** [comment]
fixed! as well as the foreclosure one, can you please review the PF?

**Comment by anu-007** [comment]
@jhonatanbds I checked out new_reskin branch for this issue and found it is not fixed here is the screenshot.

![alt text](https://github.com/anu-007/assets/blob/master/Screenshot%20from%202017-03-19%2021-49-05.png?raw=true "before")

fixed it via ( https://github.com/openMF/community-app/pull/2119 ) @santoshmath @mbj36  please review.

**Comment by jhonatanbds** [comment]
did you checked my branch? @anu-007

**Comment by mbj36** [comment]
@santoshmath can you give more update on it ?

**Comment by santoshmath** [comment]
@mbj36, Create an user with Role and permissions related to loans (In Manage Roles and permissions, provide all permissions related to loan and loan reschedule, namely, Loan_reschedule, Portfolio and Loan transactions). Then, login with that user and try to reschedule loan. On Loan Reschedule page, 'Submit' button is not displaying. 
This is critical issue.

**Comment by mbj36** [comment]
@santoshmath

**Comment by santoshmath** [comment]
Tested it on 5/6/2017 on new_reskin branch. This issue is fixed.
